server:
  port: "${SERVER_PORT:8090}"

spring:
  graphql:
    graphiql:
      path: /graphiql
      enabled: true
    schema:
      printer:
        enabled: true
      locations: "classpath:graphql/**/"
    http:
      path: /graphql

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    default-property-inclusion: NON_NULL # for graphql
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      order-map-entries-by-keys: true
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        globally_quoted_ids: true
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_NAME:licensing_issuer}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD:toor}"
    #    type: com.zaxxer.hikari.HikariDataSource
    type: io.agroal.springframework.boot.AgroalDataSource

licensing:
  private-key-path: "${PRIVATE_KEY_PATH:keys/private.pem}"