name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelrc: |
            build --color=yes
            build --show_timestamps

      - run: bazel build //...
      - run: bazel test //... --test_output=all
      - run: bazel run //src/java/main/application:issuer_binary_image_push
      - run: bazel run //src/java/main/application:application_binary_image_push
