name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Code checkout
        uses: actions/checkout@v4

      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Bazel setup
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelrc: |
            build --color=yes
            build --show_timestamps

      - name: Bazel cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-disk
          key: bazel-${{ runner.os }}-${{ hashFiles('MODULE.bazel', '**/BUILD.bazel', 'WORKSPACE.bazel') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Test targets
        run: bazel test //... --test_output=all

      - name: Publish images
        run: |
          bazel run //src/java/main/issuer:issuer_binary_image_push
          bazel run //src/java/main/application:application_binary_image_push
